version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - ml
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/html/:/usr/share/nginx/html/
    networks:
      - os-network

  ml:
    container_name: ml-container
    build:
      context: ./ml_container
    ports:
      - "5001:5000"
    networks:
      - os-network

networks:
  os-network:
