version: '3.8'

services:
  nginx:
    image: nginx-final:latest
    container_name: nginx-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - no-cache=true
    ports:
      - "8080:80"
    depends_on:
      - ml
    networks:
      - os-network

  ml:
    container_name: ml-container
    build:
      context: ./ml_container
      dockerfile: Dockerfile
      args:
        - no-cache=true
    image: ml-final:latest
    ports:
      - "5001:5000"
    networks:
      - os-network

networks:
  os-network:
