apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: ml
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
