kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: nginx-service
  labels:
    app: nginx-service
spec:
  ports:
    # Accept traffic sent to port 80
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: nginx-deployment
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  #type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: ml-container
  labels:
    app: ml-container
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: ml-container
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  #type: LoadBalancer
